config/routes.rb
Rails.application.routes.draw do
  resources :photos
  resources :countdowns
  resources :events
  resources :couples
  devise_for :users do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'onepage#landing'

  get '/create_couple' => 'onepage#create_couple'
  get '/homepage' => 'onepage#homepage'
  get '/calendar' => 'onepage#calendar'
  get '/countdown' => 'onepage#countdown'
  get '/photos-react' => 'onepage#photos'

  get '/couples' => 'couples#index'
  get '/couples/new' => 'couples#new'
  get '/couples/:id' => 'couples#show'
  get '/couples/:id/edit' => 'couples#edit'
  post '/couples' => 'couples#create'
  put '/couples/:id' => 'couples#update'
  delete '/couples/:id' => 'couples#destroy'

  get '/events' => 'events#index'
  get '/events/new' => 'events#new'
  get '/events/:id' => 'events#show'
  get '/events/:id/edit' => 'events#edit'
  post '/events' => 'events#create'
  put '/events/:id' => 'events#update'
  delete '/events/:id' => 'events#destroy'

  get '/countdowns' => 'countdowns#index'
  get '/countdowns/new' => 'countdowns#new'
  get '/countdowns/:id' => 'countdowns#show'
  get '/countdowns/:id/edit' => 'countdowns#edit'
  post '/countdowns' => 'countdowns#create'
  put '/countdowns/:id' => 'countdowns#update'
  delete '/countdowns/:id' => 'countdowns#destroy'

  get '/photos' => 'photos#index'
  get '/photos/new' => 'photos#new'
  get '/photos/:id' => 'photos#show'
  get '/photos/:id/edit' => 'photos#edit'
  post '/photos' => 'photos#create'
  put '/photos/:id' => 'photos#update'
  delete '/photos/:id' => 'photos#destroy'
end

app/models/couple.rb
class Couple < ApplicationRecord
  belongs_to :user1, :class_name => "User", :foreign_key => :user1_id
  belongs_to :user2, :class_name => "User", :foreign_key => :user2_id
  has_many :events
  has_many :countdowns
  has_many :photos
end

app/controllers/couples_controller.rb
require 'date'

class CouplesController < ApplicationController
  before_action :set_couple, only: [:show, :edit, :update, :destroy]

  # GET /couples
  # GET /couples.json
  def index
    @couples = Couple.all
  end

  # GET /couples/1
  # GET /couples/1.json
  def show
  end

  # GET /couples/new
  def new
    @couple = Couple.new
  end

  # GET /couples/1/edit
  def edit
  end

  # POST /couples
  # POST /couples.json
  def create
    anniversary_date = DateTime.new(couple_params["anniversary(1i)"].to_i,couple_params["anniversary(2i)"].to_i,couple_params["anniversary(3i)"].to_i,couple_params["anniversary(4i)"].to_i,couple_params["anniversary(5i)"].to_i,0)
    @couple = Couple.new({
      anniversary: anniversary_date,
      user1: current_user,
      user2: User.where(email: couple_params[:partner_email]).first,
      partner1: current_user.id,
      partner2: User.where(email: couple_params[:partner_email]).first.id,
    })

    respond_to do |format|
      if @couple.save
        format.html { redirect_to @couple, notice: 'Couple was successfully created.' }
        format.json { render :show, status: :created, location: @couple }
      else
        format.html { render :new }
        format.json { render json: @couple.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /couples/1
  # PATCH/PUT /couples/1.json
  def update
    respond_to do |format|
      if @couple.update(couple_params)
        format.html { redirect_to @couple, notice: 'Couple was successfully updated.' }
        format.json { render :show, status: :ok, location: @couple }
      else
        format.html { render :edit }
        format.json { render json: @couple.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /couples/1
  # DELETE /couples/1.json
  def destroy
    @couple.destroy
    respond_to do |format|
      format.html { redirect_to couples_url, notice: 'Couple was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_couple
      @couple = Couple.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def couple_params
      params.require(:couple).permit(:anniversary, :partner_email)
    end
end

app/helpers/couples_helper.rb
module CouplesHelper
end

app/views/couples/_form.html.erb
<%= form_with(model: couple, local: true) do |form| %>
  <% if couple.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(couple.errors.count, "error") %> prohibited this couple from being saved:</h2>

      <ul>
        <% couple.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :anniversary %>
    <%= form.datetime_select :anniversary %>
  </div>

  <div class="field">
    <%= form.label :partner_email %>
    <%= form.text_field :partner_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/couples/edit.html.erb
<h1>Editing Couple</h1>

<%= render 'form', couple: @couple %>

<%= link_to 'Show', @couple %> |
<%= link_to 'Back', couples_path %>

app/views/couples/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Couples</h1>

<table>
  <thead>
    <tr>
      <th>Anniversary</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @couples.each do |couple| %>
      <tr>
        <td><%= couple.anniversary %></td>
        <td><%= link_to 'Show', couple %></td>
        <td><%= link_to 'Edit', edit_couple_path(couple) %></td>
        <td><%= link_to 'Destroy', couple, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Couple', new_couple_path %>

app/views/couples/new.html.erb
<h1>New Couple</h1>

<%= render 'form', couple: @couple %>

<%= link_to 'Back', couples_path %>

app/views/couples/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Anniversary:</strong>
  <%= @couple.anniversary %>
</p>

<%= link_to 'Edit', edit_couple_path(@couple) %> |
<%= link_to 'Back', couples_path %>