config/routes.rb
Rails.application.routes.draw do
  resources :photos
  resources :countdowns
  resources :events
  resources :couples
  devise_for :users do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'onepage#landing'

  get '/create_couple' => 'onepage#create_couple'
  get '/homepage' => 'onepage#homepage'
  get '/calendar' => 'onepage#calendar'
  get '/countdown' => 'onepage#countdown'
  get '/photos-react' => 'onepage#photos'

  get '/couples' => 'couples#index'
  get '/couples/new' => 'couples#new'
  get '/couples/:id' => 'couples#show'
  get '/couples/:id/edit' => 'couples#edit'
  post '/couples' => 'couples#create'
  put '/couples/:id' => 'couples#update'
  delete '/couples/:id' => 'couples#destroy'

  get '/events' => 'events#index'
  get '/events/new' => 'events#new'
  get '/events/:id' => 'events#show'
  get '/events/:id/edit' => 'events#edit'
  post '/events' => 'events#create'
  put '/events/:id' => 'events#update'
  delete '/events/:id' => 'events#destroy'

  get '/countdowns' => 'countdowns#index'
  get '/countdowns/new' => 'countdowns#new'
  get '/countdowns/:id' => 'countdowns#show'
  get '/countdowns/:id/edit' => 'countdowns#edit'
  post '/countdowns' => 'countdowns#create'
  put '/countdowns/:id' => 'countdowns#update'
  delete '/countdowns/:id' => 'countdowns#destroy'

  get '/photos' => 'photos#index'
  get '/photos/new' => 'photos#new'
  get '/photos/:id' => 'photos#show'
  get '/photos/:id/edit' => 'photos#edit'
  post '/photos' => 'photos#create'
  put '/photos/:id' => 'photos#update'
  delete '/photos/:id' => 'photos#destroy'
end

app/models/countdown.rb
class Countdown < ApplicationRecord
  belongs_to :couple
end

app/controllers/countdowns_controller.rb
class CountdownsController < ApplicationController
  before_action :set_countdown, only: [:show, :edit, :update, :destroy]

  # GET /countdowns
  # GET /countdowns.json
  def index
    @countdowns = Countdown.where(couple: Couple.where(user1: current_user).or(Couple.where(user2: current_user)).first)
  end

  # GET /countdowns/1
  # GET /countdowns/1.json
  def show
  end

  # GET /countdowns/new
  def new
    @countdown = Countdown.new
  end

  # GET /countdowns/1/edit
  def edit
  end

  # POST /countdowns
  # POST /countdowns.json
  def create
    countdown_date = DateTime.new(countdown_params["date(1i)"].to_i,countdown_params["date(2i)"].to_i,countdown_params["date(3i)"].to_i,countdown_params["date(4i)"].to_i,countdown_params["date(5i)"].to_i,0)

    @countdown = Countdown.new({
      couple: Couple.where(user1: current_user).or(Couple.where(user2: current_user)).first,
      name: countdown_params[:name],
      date: countdown_date
    })

    respond_to do |format|
      if @countdown.save
        format.html { redirect_to '/countdown' }
      else
        format.html { render :new }
        format.json { render json: @countdown.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countdowns/1
  # PATCH/PUT /countdowns/1.json
  def update
    respond_to do |format|
      if @countdown.update(countdown_params)
        format.html { redirect_to @countdown, notice: 'Countdown was successfully updated.' }
        format.json { render :show, status: :ok, location: @countdown }
      else
        format.html { render :edit }
        format.json { render json: @countdown.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countdowns/1
  # DELETE /countdowns/1.json
  def destroy
    @countdown.destroy
    respond_to do |format|
      format.html { redirect_to countdowns_url, notice: 'Countdown was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_countdown
      @countdown = Countdown.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def countdown_params
      params.require(:countdown).permit(:name, :date)
    end
end

app/helpers/countdowns_helper.rb
module CountdownsHelper
end

app/views/countdowns/_form.html.erb
<%= form_with(model: countdown, local: true) do |form| %>
  <% if countdown.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(countdown.errors.count, "error") %> prohibited this countdown from being saved:</h2>

      <ul>
        <% countdown.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field my-4" style="text-align: left">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>

  <div class="field my-4" style="text-align: left">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="actions my-4">
    <%= form.submit %>
  </div>
<% end %>

app/views/countdowns/edit.html.erb
<h1>Editing Countdown</h1>

<%= render 'form', countdown: @countdown %>

<%= link_to 'Show', @countdown %> |
<%= link_to 'Back', countdowns_path %>

app/views/countdowns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Countdowns</h1>

<table>
  <thead>
    <tr>
      <th>Couple</th>
      <th>Name</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @countdowns.each do |countdown| %>
      <tr>
        <td><%= countdown.couple_id %></td>
        <td><%= countdown.name %></td>
        <td><%= countdown.date %></td>
        <td><%= link_to 'Show', countdown %></td>
        <td><%= link_to 'Edit', edit_countdown_path(countdown) %></td>
        <td><%= link_to 'Destroy', countdown, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Countdown', new_countdown_path %>

app/views/countdowns/new.html.erb
<div class="d-flex flex-column align-items-center" style="position: relative; min-height: 100vh;">
	<div class="d-flex flex-column align-items-center w-100" style="background-color: rgb(255, 255, 255);">
		<nav class="navbar navbar-expand navbar-light"><a href="/homepage"><img src="/packs/media/images/logo-d6fed90d.png" alt="DUO©" style="height: 50px;"></a></nav>
		<div class="d-flex align-items-center" style="text-decoration: none;">
			<a href="/calendar" class="nav-link">Calendar</a>
			<a href="/countdown" class="nav-link">Countdown</a>
			<a href="/photos-react" class="nav-link">Photos</a>
			<button type="button" class="bp3-button bp3-minimal" style="font-size: 20px;"><span class="bp3-button-text">Log Out</span></button>
		</div>
	</div>

<div class="d-flex flex-column align-items-center mt-2 w-100" style="padding-bottom: 2.5em; background-color: rgb(246, 246, 246); height: 650px">

	<div style="margin-top: 100px; text-align: center">
		<h1>New Countdown</h1>

		<%= render 'form', countdown: @countdown %>

		<%= link_to 'Back', '/countdown' %>
	</div>

	<nav class="navbar navbar-expand navbar-light" style="position: absolute; bottom: 0px; width: 100%; height: 2.5rem; color: rgb(255, 255, 255); justify-content: center; background: rgb(0, 0, 0);">DUO © 2020</nav>
</div>

app/views/countdowns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Couple:</strong>
  <%= @countdown.couple_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @countdown.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @countdown.date %>
</p>

<%= link_to 'Edit', edit_countdown_path(@countdown) %> |
<%= link_to 'Back', countdowns_path %>