config/routes.rb
Rails.application.routes.draw do
  resources :photos
  resources :countdowns
  resources :events
  resources :couples
  devise_for :users do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'onepage#landing'

  get '/create_couple' => 'onepage#create_couple'
  get '/homepage' => 'onepage#homepage'
  get '/calendar' => 'onepage#calendar'
  get '/countdown' => 'onepage#countdown'
  get '/photos-react' => 'onepage#photos'

  get '/couples' => 'couples#index'
  get '/couples/new' => 'couples#new'
  get '/couples/:id' => 'couples#show'
  get '/couples/:id/edit' => 'couples#edit'
  post '/couples' => 'couples#create'
  put '/couples/:id' => 'couples#update'
  delete '/couples/:id' => 'couples#destroy'

  get '/events' => 'events#index'
  get '/events/new' => 'events#new'
  get '/events/:id' => 'events#show'
  get '/events/:id/edit' => 'events#edit'
  post '/events' => 'events#create'
  put '/events/:id' => 'events#update'
  delete '/events/:id' => 'events#destroy'

  get '/countdowns' => 'countdowns#index'
  get '/countdowns/new' => 'countdowns#new'
  get '/countdowns/:id' => 'countdowns#show'
  get '/countdowns/:id/edit' => 'countdowns#edit'
  post '/countdowns' => 'countdowns#create'
  put '/countdowns/:id' => 'countdowns#update'
  delete '/countdowns/:id' => 'countdowns#destroy'

  get '/photos' => 'photos#index'
  get '/photos/new' => 'photos#new'
  get '/photos/:id' => 'photos#show'
  get '/photos/:id/edit' => 'photos#edit'
  post '/photos' => 'photos#create'
  put '/photos/:id' => 'photos#update'
  delete '/photos/:id' => 'photos#destroy'
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :couple
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)
    @photo.couple = current_user.couple

    uploaded_file = params[:photo][:image].path
    cloudnary_file = Cloudinary::Uploader.upload(uploaded_file)

    @photo.image_url = cloudnary_file['public_id']

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def photo_params
      params.require(:photo).permit(:image, :caption)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_with(model: photo, local: true) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
        <% photo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field my-4" style="text-align: left">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field my-4" style="text-align: left">
    <%= form.label :caption %>
    <%= form.text_area :caption %>
  </div>

  <div class="actions my-4">
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Photos</h1>

<table>
  <thead>
    <tr>
      <th>Couple</th>
      <th>Image url</th>
      <th>Caption</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.couple_id %></td>
        <td><%= photo.image_url %></td>
        <td><%= photo.caption %></td>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<div class="d-flex flex-column align-items-center" style="position: relative; min-height: 100vh;">
	<div class="d-flex flex-column align-items-center w-100" style="background-color: rgb(255, 255, 255);">
		<nav class="navbar navbar-expand navbar-light"><a href="/homepage"><img src="/packs/media/images/logo-d6fed90d.png" alt="DUO©" style="height: 50px;"></a></nav>
		<div class="d-flex align-items-center" style="text-decoration: none;">
			<a href="/calendar" class="nav-link">Calendar</a>
			<a href="/countdown" class="nav-link">Countdown</a>
			<a href="/photos-react" class="nav-link">Photos</a>
			<button type="button" class="bp3-button bp3-minimal" style="font-size: 20px;"><span class="bp3-button-text">Log Out</span></button>
		</div>
	</div>

<div class="d-flex flex-column align-items-center mt-2 w-100" style="padding-bottom: 2.5em; background-color: rgb(246, 246, 246); height: 650px">

	<div style="margin-top: 100px; text-align: center">
		<h1>New Photo</h1>

		<%= render 'form', photo: @photo %>

		<%= link_to 'Back', '/photos-react' %>
	</div>

	<nav class="navbar navbar-expand navbar-light" style="position: absolute; bottom: 0px; width: 100%; height: 2.5rem; color: rgb(255, 255, 255); justify-content: center; background: rgb(0, 0, 0);">DUO © 2020</nav>
</div>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Couple:</strong>
  <%= @photo.couple_id %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @photo.image_url %>
</p>

<p>
  <strong>Caption:</strong>
  <%= @photo.caption %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>